/**
 * Cheat Sheet Data - Web Application Development (Node, Express, HTML, JS)
 * Each item: category, item, syntax, description, returnType (optional), details, tag (HTML only)
 */
export const cheatSheetData = [
  // ========== JS Types & Quirks ==========
  {
    category: 'JS Types & Quirks',
    item: 'typeof null',
    syntax: 'typeof null',
    description: 'Type check for null value.',
    returnType: '"object"',
    details: 'typeof null returns "object" — this is a known JavaScript bug/historical quirk. Null is not an object.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'typeof undefined',
    syntax: 'typeof undefined',
    description: 'Type check for undefined.',
    returnType: '"undefined"',
    details: 'typeof undefined returns "undefined". Use when checking if a variable has not been assigned.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'typeof NaN',
    syntax: 'typeof NaN',
    description: 'Type check for NaN (Not a Number).',
    returnType: '"number"',
    details: 'typeof NaN returns "number". NaN is of type number but represents an invalid numeric result.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'typeof string',
    syntax: 'typeof "hello"',
    description: 'Type check for string.',
    returnType: '"string"',
    details: 'typeof returns "string" for string primitives and String values.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'typeof number',
    syntax: 'typeof 42',
    description: 'Type check for number.',
    returnType: '"number"',
    details: 'typeof returns "number" for numbers including NaN and Infinity.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'typeof boolean',
    syntax: 'typeof true',
    description: 'Type check for boolean.',
    returnType: '"boolean"',
    details: 'typeof returns "boolean" for true and false.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'typeof function',
    syntax: 'typeof function() {}',
    description: 'Type check for function.',
    returnType: '"function"',
    details: 'typeof returns "function" for functions. Functions are technically objects but typeof distinguishes them.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'typeof object',
    syntax: 'typeof {}  |  typeof []',
    description: 'Type check for object (and arrays).',
    returnType: '"object"',
    details: 'typeof {} and typeof [] both return "object". Use Array.isArray() to distinguish arrays.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'isNaN() vs Number.isNaN()',
    syntax: 'isNaN(x)  |  Number.isNaN(x)',
    description: 'Checking if a value is NaN.',
    returnType: 'boolean',
    details: 'isNaN() coerces the argument to a number first — isNaN("hello") is true. Number.isNaN() does not coerce — Number.isNaN("hello") is false. Use Number.isNaN() for strict NaN check.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'Object.is()',
    syntax: 'Object.is(a, b)',
    description: 'Strict equality check (same as === except NaN and ±0).',
    returnType: 'boolean',
    details: 'Object.is(NaN, NaN) is true; NaN === NaN is false. Object.is(0, -0) is false; 0 === -0 is true.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'Truthy values',
    syntax: 'Truthy: non-empty values that evaluate to true',
    description: 'Values that evaluate to true in boolean context.',
    returnType: 'N/A',
    details: 'Truthy: true, non-zero numbers, non-empty strings "", [], {}, (and most values). Falsy: false, 0, -0, 0n, "", null, undefined, NaN.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'Falsy values',
    syntax: 'Falsy: false, 0, "", null, undefined, NaN',
    description: 'Values that evaluate to false in boolean context.',
    returnType: 'N/A',
    details: 'The six falsy values: false, 0 (and -0, 0n), "" (empty string), null, undefined, NaN. Everything else is truthy.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'Loose equality (==)',
    syntax: 'a == b',
    description: 'Compares with type coercion.',
    returnType: 'boolean',
    details: '== (loose equality) coerces types before comparing. Example: 5 == "5" is true. Can lead to surprising results; prefer ===.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'Strict equality (===)',
    syntax: 'a === b',
    description: 'Compares without type coercion.',
    returnType: 'boolean',
    details: '=== (strict equality) compares value and type. No coercion. Example: 5 === "5" is false. Preferred for predictable comparisons.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'null vs undefined',
    syntax: 'null  |  undefined',
    description: 'Two "empty" values; different meanings.',
    returnType: 'N/A',
    details: 'undefined = not assigned / missing. null = intentionally empty. Both are falsy. typeof null is "object", typeof undefined is "undefined".',
  },
  {
    category: 'JS Types & Quirks',
    item: 'Primitive vs object',
    syntax: 'Primitives: string, number, boolean, null, undefined, symbol, bigint',
    description: 'Primitives are immutable and compared by value; objects by reference.',
    returnType: 'N/A',
    details: 'Primitives are not objects (except typeof null bug). Objects (including arrays, functions) are compared by reference.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'Boolean conversion',
    syntax: 'Boolean(x)  |  !!x',
    description: 'Convert any value to boolean.',
    returnType: 'boolean',
    details: 'Boolean(x) or !!x converts to true/false. Only falsy values become false; all others true.',
  },
  {
    category: 'JS Types & Quirks',
    item: 'Array.isArray()',
    syntax: 'Array.isArray(x)',
    description: 'Check if value is an array.',
    returnType: 'boolean',
    details: 'typeof [] is "object". Array.isArray([]) is true, Array.isArray({}) is false. Use for reliable array check.',
  },

  // ========== JS Variables ==========
  {
    category: 'JS Variables',
    item: 'var',
    syntax: 'var x = 1;',
    description: 'Function-scoped, hoisted variable.',
    returnType: 'N/A',
    details: 'var is function-scoped (not block-scoped). It is hoisted: declaration is moved to top of function. Can be redeclared. Prefer let/const in modern JS.',
  },
  {
    category: 'JS Variables',
    item: 'let',
    syntax: 'let x = 1;',
    description: 'Block-scoped variable, can be reassigned.',
    returnType: 'N/A',
    details: 'let is block-scoped (inside {}). Not hoisted in same way as var (temporal dead zone). Can be reassigned but not redeclared in same scope.',
  },
  {
    category: 'JS Variables',
    item: 'const',
    syntax: 'const x = 1;',
    description: 'Block-scoped, immutable binding.',
    returnType: 'N/A',
    details: 'const is block-scoped. Must be initialized at declaration. The reference is immutable (cannot reassign), but object/array contents can still be mutated.',
  },
  {
    category: 'JS Variables',
    item: 'Object/Array assignment by reference',
    syntax: 'let a = [1,2]; let b = a;',
    description: 'Objects and arrays are assigned by reference, not by value.',
    returnType: 'N/A',
    details: 'When you assign an object or array to another variable, both point to the same reference. Mutating one affects the other. Use spread/copy to clone.',
  },
  {
    category: 'JS Variables',
    item: 'Temporal dead zone (TDZ)',
    syntax: 'let x = 1; { console.log(x); let x = 2; }',
    description: 'let/const are not accessible before declaration in block.',
    returnType: 'N/A',
    details: 'Accessing let or const before the line that declares it (in same block) throws ReferenceError. var would be undefined.',
  },
  {
    category: 'JS Variables',
    item: 'Block scope',
    syntax: '{ let x = 1; }  console.log(x); // ReferenceError',
    description: 'let and const are scoped to the block (any {}).',
    returnType: 'N/A',
    details: 'Block = if, for, while, switch body or bare {}. Variables inside are not visible outside. var is only function-scoped.',
  },
  {
    category: 'JS Variables',
    item: 'Redeclaration',
    syntax: 'var x = 1; var x = 2;  // OK.  let x = 1; let x = 2;  // SyntaxError',
    description: 'var can be redeclared; let/const cannot in same scope.',
    returnType: 'N/A',
    details: 'In same scope, let and const cannot be redeclared. var can, which can cause bugs.',
  },
  {
    category: 'JS Variables',
    item: 'Global scope',
    syntax: 'var in global becomes window.property (browser); let/const do not.',
    description: 'Top-level var attaches to global object; let/const do not.',
    returnType: 'N/A',
    details: 'In browser, var x at top level → window.x. let/const at top level are global but not on window.',
  },
  {
    category: 'JS Variables',
    item: 'Shallow copy array',
    syntax: 'const b = [...a];  or  const b = a.slice();',
    description: 'Copy array so mutations do not affect original.',
    returnType: 'N/A',
    details: 'Spread or slice() creates new array. Elements are still same references (shallow). For deep copy need recursive or library.',
  },
  {
    category: 'JS Variables',
    item: 'Shallow copy object',
    syntax: 'const b = { ...a };  or  Object.assign({}, a)',
    description: 'Copy object so mutations do not affect original.',
    returnType: 'N/A',
    details: 'Spread or Object.assign creates new object; nested objects are still shared (shallow copy).',
  },

  // ========== JS Loops ==========
  {
    category: 'JS Loops',
    item: 'for loop',
    syntax: 'for (let i = 0; i < arr.length; i++) { }',
    description: 'Classic loop with init, condition, update.',
    returnType: 'N/A',
    details: 'for (init; condition; update) — init runs once; condition checked each iteration; update after body. Use let/const for loop variable to keep block scope.',
  },
  {
    category: 'JS Loops',
    item: 'while loop',
    syntax: 'while (condition) { }',
    description: 'Repeats while condition is true.',
    returnType: 'N/A',
    details: 'Condition checked before each iteration. Ensure condition eventually becomes false to avoid infinite loop.',
  },
  {
    category: 'JS Loops',
    item: 'do...while loop',
    syntax: 'do { } while (condition);',
    description: 'Runs body at least once, then repeats while condition is true.',
    returnType: 'N/A',
    details: 'Condition checked after each iteration. Body always runs at least once.',
  },
  {
    category: 'JS Loops',
    item: 'for...of loop',
    syntax: 'for (const item of arr) { }',
    description: 'Iterates over iterable values (arrays, strings, etc.).',
    returnType: 'N/A',
    details: 'for...of gives each value (element). Use for arrays, strings, Map values, Set. Not for plain objects; use for...in or Object.keys().',
  },
  {
    category: 'JS Loops',
    item: 'for...in loop',
    syntax: 'for (const key in obj) { }',
    description: 'Iterates over enumerable property keys of an object.',
    returnType: 'N/A',
    details: 'for...in gives keys (property names). Use for plain objects. For arrays prefer for...of (for...in can include inherited/enumerable props).',
  },
  {
    category: 'JS Loops',
    item: 'break',
    syntax: 'break;',
    description: 'Exits the current loop or switch immediately.',
    returnType: 'N/A',
    details: 'break exits only the innermost loop/switch. Use labeled statement for nested: label: for(...) { break label; }.',
  },
  {
    category: 'JS Loops',
    item: 'continue',
    syntax: 'continue;',
    description: 'Skips to next iteration of the current loop.',
    returnType: 'N/A',
    details: 'continue skips rest of loop body for current iteration. In for loop, update expression still runs.',
  },

  // ========== JS Arrays & Strings ==========
  {
    category: 'JS Arrays & Strings',
    item: 'length',
    syntax: 'arr.length',
    description: 'Number of elements in the array (or string length).',
    returnType: 'number',
    details: 'Read-only for strings. For arrays, length is a property: setting arr.length = 0 truncates; setting larger extends (empty slots). arr.length returns number of elements.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'push',
    syntax: 'arr.push(item1, item2, ...)',
    description: 'Adds one or more elements to the end of an array.',
    returnType: 'New length of array (number)',
    details: 'Mutates the array. Returns the new length. push returns new length.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'pop',
    syntax: 'arr.pop()',
    description: 'Removes the last element from an array.',
    returnType: 'The removed element (or undefined if empty)',
    details: 'Mutates the array. pop returns the removed item.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'shift',
    syntax: 'arr.shift()',
    description: 'Removes the first element from an array.',
    returnType: 'The removed element (or undefined if empty)',
    details: 'Mutates the array. shift returns the removed item.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'unshift',
    syntax: 'arr.unshift(item1, item2, ...)',
    description: 'Adds one or more elements to the beginning of an array.',
    returnType: 'New length of array (number)',
    details: 'Mutates the array. unshift returns the new length.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'slice',
    syntax: 'arr.slice(start, end)',
    description: 'Returns a shallow copy of a portion of the array.',
    returnType: 'New array (copy)',
    details: 'Non-mutating. slice does not modify the original array. end is exclusive. Omit end to go to end.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'splice',
    syntax: 'arr.splice(start, deleteCount, ...items)',
    description: 'Changes array by removing/replacing elements and/or adding new elements.',
    returnType: 'Array of removed elements',
    details: 'Mutating. splice modifies the original array. Returns array of removed elements. Use for insert, delete, or replace in place.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'map',
    syntax: 'arr.map(callback)',
    description: 'Creates a new array with results of calling callback on every element.',
    returnType: 'New array',
    details: 'Non-mutating. map returns a new array of same length. Each element is the return value of the callback.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'filter',
    syntax: 'arr.filter(callback)',
    description: 'Creates a new array with elements that pass the callback test.',
    returnType: 'New array',
    details: 'Non-mutating. filter returns a new array containing only elements where callback returns truthy.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'reduce',
    syntax: 'arr.reduce(callback, initialValue)',
    description: 'Reduces array to a single value by applying callback left to right.',
    returnType: 'The accumulated value (any type)',
    details: 'reduce returns whatever the final accumulator value is. Callback receives (acc, current, index, array).',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'forEach',
    syntax: 'arr.forEach(callback)',
    description: 'Executes callback once for each array element.',
    returnType: 'undefined',
    details: 'forEach returns undefined. Use for side effects only; cannot break or return a value from forEach.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'join',
    syntax: 'arr.join(separator)',
    description: 'Joins all elements into a string with optional separator.',
    returnType: 'String',
    details: 'join returns a string. Default separator is comma. Empty string "" joins with no separator.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'split',
    syntax: 'str.split(separator, limit)',
    description: 'Splits a string into an array of substrings.',
    returnType: 'Array of strings',
    details: 'split returns an array. separator can be string or regex. limit caps the number of splits.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'indexOf',
    syntax: 'arr.indexOf(value)  |  str.indexOf(searchValue)',
    description: 'Returns first index at which value is found, or -1.',
    returnType: 'Number (index or -1)',
    details: 'indexOf returns the index of first occurrence, or -1 if not found. Uses strict equality (===).',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'includes',
    syntax: 'arr.includes(value)  |  str.includes(searchValue)',
    description: 'Returns true if array/string contains the value.',
    returnType: 'boolean',
    details: 'includes returns true or false. More readable than indexOf !== -1 for existence checks.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'concat',
    syntax: 'arr.concat(arr2, ...)  |  str.concat(str2, ...)',
    description: 'Combines arrays or strings; does not mutate original.',
    returnType: 'New array or string',
    details: 'concat returns a new array/string. Non-mutating. Prefer spread [...a, ...b] for arrays.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'reverse',
    syntax: 'arr.reverse()',
    description: 'Reverses array in place.',
    returnType: 'Same array (mutated)',
    details: 'Mutates the array. reverse returns a reference to the same array (reversed).',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'sort',
    syntax: 'arr.sort()  |  arr.sort(compareFn)',
    description: 'Sorts array in place. Without compareFn, sorts as strings.',
    returnType: 'Same array (mutated)',
    details: 'Mutates array. Default sort() converts to string and sorts lexicographically. For numbers use (a,b) => a - b.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'find',
    syntax: 'arr.find(callback)',
    description: 'Returns first element that satisfies callback, or undefined.',
    returnType: 'Element or undefined',
    details: 'find returns the first element where callback returns truthy. Stops when found. Returns undefined if none.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'findIndex',
    syntax: 'arr.findIndex(callback)',
    description: 'Returns index of first element that satisfies callback, or -1.',
    returnType: 'Number (index or -1)',
    details: 'findIndex returns index of first match, or -1. Like indexOf but with predicate.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'some',
    syntax: 'arr.some(callback)',
    description: 'Returns true if at least one element passes the test.',
    returnType: 'boolean',
    details: 'some returns true as soon as callback returns true for one element; otherwise false.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'every',
    syntax: 'arr.every(callback)',
    description: 'Returns true if all elements pass the test.',
    returnType: 'boolean',
    details: 'every returns false as soon as callback returns falsy for one element; otherwise true (empty array → true).',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'flat',
    syntax: 'arr.flat(depth)',
    description: 'Flattens nested arrays. Default depth 1.',
    returnType: 'New array',
    details: 'flat returns new array with subarrays concatenated. depth defaults to 1. flat(Infinity) for full flatten.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'flatMap',
    syntax: 'arr.flatMap(callback)',
    description: 'map then flat(1) in one step.',
    returnType: 'New array',
    details: 'flatMap runs callback and flattens result by one level. Equivalent to map().flat(1).',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'lastIndexOf',
    syntax: 'arr.lastIndexOf(value)  |  str.lastIndexOf(searchValue)',
    description: 'Returns last index at which value is found, or -1.',
    returnType: 'Number (index or -1)',
    details: 'lastIndexOf searches from end. Returns last occurrence index or -1.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'trim',
    syntax: 'str.trim()  |  str.trimStart()  |  str.trimEnd()',
    description: 'Removes whitespace from ends of string.',
    returnType: 'New string',
    details: 'trim returns new string with leading/trailing whitespace removed. Non-mutating. trimStart/trimEnd for one side.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'toLowerCase / toUpperCase',
    syntax: 'str.toLowerCase()  |  str.toUpperCase()',
    description: 'Returns string in lower or upper case.',
    returnType: 'New string',
    details: 'Both return new string; do not mutate original. Useful for case-insensitive comparison.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'startsWith / endsWith',
    syntax: 'str.startsWith(s)  |  str.endsWith(s)',
    description: 'Check if string starts or ends with substring.',
    returnType: 'boolean',
    details: 'Optional second argument is position to start checking from.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'replace',
    syntax: 'str.replace(search, replacement)',
    description: 'Replaces first match of search (string or regex) with replacement.',
    returnType: 'New string',
    details: 'replace returns new string. Only first match replaced unless regex with g flag. Non-mutating.',
  },
  {
    category: 'JS Arrays & Strings',
    item: 'substring / substr / slice (string)',
    syntax: 'str.substring(start, end)  |  str.slice(start, end)',
    description: 'Extract portion of string. end exclusive.',
    returnType: 'New string',
    details: 'substring and slice similar; slice can use negative indices. substr is deprecated. All return new string.',
  },

  // ========== HTML (with tag for drill-down) ==========
  { category: 'HTML', tag: 'form', item: 'Form action', syntax: '<form action="url">', description: 'URL where form data is submitted.', returnType: 'N/A', details: 'action attribute: the endpoint or page that receives the form submission (e.g. /submit or script URL).' },
  { category: 'HTML', tag: 'form', item: 'Form method GET vs POST', syntax: '<form method="GET">  |  <form method="POST">', description: 'HTTP method used to submit the form.', returnType: 'N/A', details: 'GET: data in URL query string (visible, bookmarkable). POST: data in request body (not in URL, for sensitive or large data).' },
  { category: 'HTML', tag: 'form', item: 'Form name', syntax: 'name="fieldName"', description: 'Name of the form or form control; used when submitting data.', returnType: 'N/A', details: 'name is sent with form data (key in key-value pairs). Required for form controls to be submitted.' },
  { category: 'HTML', tag: 'form', item: 'Form enctype', syntax: '<form enctype="multipart/form-data">', description: 'Encoding type for form submission.', returnType: 'N/A', details: 'enctype: application/x-www-form-urlencoded (default), multipart/form-data (file uploads), text/plain.' },
  { category: 'HTML', tag: 'form', item: 'Form target', syntax: '<form target="_blank">', description: 'Where to open response: _self, _blank, _parent, _top, or frame name.', returnType: 'N/A', details: 'target="_blank" opens response in new tab/window.' },
  { category: 'HTML', tag: 'form', item: 'label', syntax: '<label for="id">Text</label>', description: 'Associates label with form control; clicking label focuses control.', returnType: 'N/A', details: 'for attribute matches id of input. Improves accessibility and UX.' },
  { category: 'HTML', tag: 'form', item: 'fieldset and legend', syntax: '<fieldset><legend>Title</legend>...</fieldset>', description: 'Group related form controls with a caption.', returnType: 'N/A', details: 'fieldset groups inputs; legend is the caption. Good for accessibility and styling.' },
  { category: 'HTML', tag: 'form', item: 'textarea', syntax: '<textarea name="msg" rows="4" cols="40">Default</textarea>', description: 'Multi-line text input.', returnType: 'N/A', details: 'Attributes: name, rows, cols, placeholder, required, readonly, disabled, maxlength, minlength. Content is initial value; submitted as name=value.' },

  { category: 'HTML', tag: 'input', item: 'id attribute', syntax: 'id="uniqueId"', description: 'Unique identifier for an element.', returnType: 'N/A', details: 'id must be unique in the document. Used for linking (anchor), CSS, and JavaScript getElementById.' },
  { category: 'HTML', tag: 'input', item: 'value attribute', syntax: 'value="initialValue"', description: 'Initial or current value of an input/option/button.', returnType: 'N/A', details: 'value is what gets submitted for that control and what is shown/used as the control\'s value.' },
  { category: 'HTML', tag: 'input', item: 'placeholder', syntax: 'placeholder="hint text"', description: 'Hint shown when input is empty.', returnType: 'N/A', details: 'placeholder is not submitted; it is only a visual hint. Do not use as replacement for <label>.' },
  { category: 'HTML', tag: 'input', item: 'required', syntax: 'required', description: 'Form cannot submit until this field has a value.', returnType: 'N/A', details: 'required is a boolean attribute. Browser validates before submit. Use for mandatory fields.' },
  { category: 'HTML', tag: 'input', item: 'readonly', syntax: 'readonly', description: 'User cannot edit the value; still submitted.', returnType: 'N/A', details: 'readonly: value is visible and submitted but not editable. Unlike disabled, readonly fields are included in form data.' },
  { category: 'HTML', tag: 'input', item: 'disabled', syntax: 'disabled', description: 'Control is disabled; not submitted with form.', returnType: 'N/A', details: 'disabled excludes the field from form submission. Value is not sent.' },
  { category: 'HTML', tag: 'input', item: 'Input type text', syntax: '<input type="text">', description: 'Single-line text input.', returnType: 'N/A', details: 'Default type. type="text" for plain single-line text.' },
  { category: 'HTML', tag: 'input', item: 'Input type radio', syntax: '<input type="radio" name="group">', description: 'Radio button; only one in a group can be selected.', returnType: 'N/A', details: 'Radio buttons are grouped by name. Same name = one selection per group. value is what gets submitted.' },
  { category: 'HTML', tag: 'input', item: 'Input type checkbox', syntax: '<input type="checkbox">', description: 'Checkbox for on/off or multiple selections.', returnType: 'N/A', details: 'Checked checkboxes submit their name and value (or "on" if no value). Unchecked boxes are not submitted.' },
  { category: 'HTML', tag: 'input', item: 'Input type submit', syntax: '<input type="submit">', description: 'Button that submits the form.', returnType: 'N/A', details: 'type="submit" sends the form. Value attribute becomes the button label.' },
  { category: 'HTML', tag: 'input', item: 'Input type hidden', syntax: '<input type="hidden" name="x" value="y">', description: 'Invisible field; value is submitted with form.', returnType: 'N/A', details: 'hidden inputs are not visible. Use for tokens, IDs, or extra data that must be sent with the form.' },
  { category: 'HTML', tag: 'input', item: 'Input type password', syntax: '<input type="password">', description: 'Text input with characters masked.', returnType: 'N/A', details: 'type="password" masks input. Value is still submitted as plain text; encrypt on server if needed.' },
  { category: 'HTML', tag: 'input', item: 'Input type email', syntax: '<input type="email">', description: 'Email input; browser may validate format.', returnType: 'N/A', details: 'type="email" can trigger keyboard and validation. Still submit to server for real validation.' },
  { category: 'HTML', tag: 'input', item: 'Input type number', syntax: '<input type="number" min="0" max="100">', description: 'Numeric input; optional min, max, step.', returnType: 'N/A', details: 'type="number" restricts to numbers. min, max, step for range. value is string in form data.' },
  { category: 'HTML', tag: 'input', item: 'Input type file', syntax: '<input type="file" accept=".pdf">', description: 'File upload. accept limits file types.', returnType: 'N/A', details: 'type="file" for uploads. Use enctype="multipart/form-data" on form. accept hints allowed types.' },
  { category: 'HTML', tag: 'input', item: 'Input type button', syntax: '<input type="button" value="Click">', description: 'Button with no default behavior.', returnType: 'N/A', details: 'type="button" does not submit form. Use for custom JS actions. Prefer <button type="button">.' },
  { category: 'HTML', tag: 'input', item: 'Input type reset', syntax: '<input type="reset">', description: 'Resets form controls to initial values.', returnType: 'N/A', details: 'type="reset" resets all fields in the form to their initial state when clicked.' },
  { category: 'HTML', tag: 'input', item: 'autofocus', syntax: 'autofocus', description: 'Focus this control when page loads.', returnType: 'N/A', details: 'Only one autofocus per page. Use sparingly for accessibility. Used on: text, number, email, password, and most input types.' },
  { category: 'HTML', tag: 'input', item: 'maxlength', syntax: 'maxlength="100"', description: 'Maximum number of characters allowed.', returnType: 'N/A', details: 'maxlength prevents typing more than the given number. Used on: text, email, password, search, tel, url. Always validate on server.' },
  { category: 'HTML', tag: 'input', item: 'minlength', syntax: 'minlength="2"', description: 'Minimum number of characters required.', returnType: 'N/A', details: 'minlength validates at least N characters. Used on: text, email, password, search, tel, url.' },
  { category: 'HTML', tag: 'input', item: 'size', syntax: 'size="20"', description: 'Visual width of input in characters (approximate).', returnType: 'N/A', details: 'size hints display width; use CSS for precise control. Used on: text, email, password, search, tel, url.' },
  { category: 'HTML', tag: 'input', item: 'step', syntax: 'step="0.1"  or  step="any"', description: 'Increment for number/range/date inputs.', returnType: 'N/A', details: 'step constrains valid values. Used on: number, range, date, datetime-local, time.' },
  { category: 'HTML', tag: 'input', item: 'min and max', syntax: 'min="0" max="100"', description: 'Minimum and maximum value for number/range/date.', returnType: 'N/A', details: 'min/max validate range. Used on: number, range, date, datetime-local, time, month, week.' },
  { category: 'HTML', tag: 'input', item: 'accept', syntax: 'accept=".pdf,image/*"', description: 'Hint for allowed file types (file input).', returnType: 'N/A', details: 'accept limits file picker; not enforced. Used on: type="file". Comma-separated MIME types or extensions.' },
  { category: 'HTML', tag: 'input', item: 'checked', syntax: 'checked  or  checked="checked"', description: 'Pre-select radio or checkbox.', returnType: 'N/A', details: 'Boolean attribute. Used on: type="radio", type="checkbox". One radio per name can be checked.' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=text', syntax: '<input type="text">', description: 'Attributes available for text input.', returnType: 'N/A', details: 'For type="text": id, name, value, placeholder, required, readonly, disabled, maxlength, minlength, size, autofocus, list, pattern, title, class.' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=number', syntax: '<input type="number">', description: 'Attributes available for number input.', returnType: 'N/A', details: 'For type="number": id, name, value, min, max, step, required, readonly, disabled, placeholder, autofocus, list, class.' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=radio', syntax: '<input type="radio" name="group">', description: 'Attributes available for radio input.', returnType: 'N/A', details: 'For type="radio": name (required for grouping), value, checked, required, disabled, autofocus. Same name = one selection per group.' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=checkbox', syntax: '<input type="checkbox">', description: 'Attributes available for checkbox input.', returnType: 'N/A', details: 'For type="checkbox": name, value, checked, required, disabled, autofocus. Unchecked boxes are not submitted.' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=email', syntax: '<input type="email">', description: 'Attributes available for email input.', returnType: 'N/A', details: 'For type="email": id, name, value, placeholder, required, readonly, disabled, maxlength, minlength, size, autofocus, multiple (for multiple emails), pattern, list.' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=password', syntax: '<input type="password">', description: 'Attributes available for password input.', returnType: 'N/A', details: 'For type="password": id, name, value, placeholder, required, readonly, disabled, maxlength, minlength, size, autofocus, pattern, title.' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=file', syntax: '<input type="file">', description: 'Attributes available for file input.', returnType: 'N/A', details: 'For type="file": name, accept, multiple, required, disabled. Form must use enctype="multipart/form-data".' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=submit', syntax: '<input type="submit" value="Send">', description: 'Attributes available for submit button.', returnType: 'N/A', details: 'For type="submit": value (button label), name (sent with form if present), disabled, form (id of form to submit).' },
  { category: 'HTML', tag: 'input', item: 'Attributes for type=hidden', syntax: '<input type="hidden" name="x" value="y">', description: 'Attributes for hidden input.', returnType: 'N/A', details: 'For type="hidden": name, value (required). Used for tokens, IDs, or extra data submitted with form.' },

  { category: 'HTML', tag: 'select', item: 'select element', syntax: '<select name="choice"><option>...</option></select>', description: 'Dropdown or list of options.', returnType: 'N/A', details: 'select creates a dropdown. name is submitted; value comes from selected option. Use multiple for multi-select. size shows N lines.' },
  { category: 'HTML', tag: 'select', item: 'option', syntax: '<option value="a">Label A</option>', description: 'One option in a select.', returnType: 'N/A', details: 'value is what gets submitted; text content is label. selected preselects. Use optgroup to group options.' },
  { category: 'HTML', tag: 'select', item: 'optgroup', syntax: '<optgroup label="Group name"><option>...</option></optgroup>', description: 'Group options in a select.', returnType: 'N/A', details: 'optgroup groups option elements. label is the group heading (not selectable).' },
  { category: 'HTML', tag: 'select', item: 'select multiple', syntax: '<select name="choices" multiple>', description: 'Allow multiple selections.', returnType: 'N/A', details: 'multiple attribute allows selecting more than one option. Submitted value is multiple name=values (depends on server).' },
  { category: 'HTML', tag: 'select', item: 'select size', syntax: 'size="4"', description: 'Number of visible options (height of list).', returnType: 'N/A', details: 'size makes select show as list box with N visible rows. Without size it is a dropdown.' },
  { category: 'HTML', tag: 'select', item: 'selected (option)', syntax: '<option value="x" selected>', description: 'Pre-select an option.', returnType: 'N/A', details: 'selected boolean attribute on option. One selected per select (or multiple if select has multiple).' },

  { category: 'HTML', tag: 'table', item: 'Table colspan', syntax: '<td colspan="2">', description: 'Cell spans multiple columns.', returnType: 'N/A', details: 'colspan merges cells horizontally. Number is how many columns the cell spans.' },
  { category: 'HTML', tag: 'table', item: 'Table rowspan', syntax: '<td rowspan="2">', description: 'Cell spans multiple rows.', returnType: 'N/A', details: 'rowspan merges cells vertically. Number is how many rows the cell spans.' },
  { category: 'HTML', tag: 'table', item: 'thead', syntax: '<thead><tr><th>...</th></tr></thead>', description: 'Table header section.', returnType: 'N/A', details: 'thead groups header rows. Use <th> for header cells. Semantic and can be styled separately.' },
  { category: 'HTML', tag: 'table', item: 'tbody', syntax: '<tbody><tr><td>...</td></tr></tbody>', description: 'Table body section.', returnType: 'N/A', details: 'tbody groups data rows. Optional but good for structure and styling.' },
  { category: 'HTML', tag: 'table', item: 'tfoot', syntax: '<tfoot><tr><td>...</td></tr></tfoot>', description: 'Table footer section (e.g. totals).', returnType: 'N/A', details: 'tfoot for footer rows. Renders after tbody in some browsers; semantic for summary rows.' },
  { category: 'HTML', tag: 'table', item: 'table structure', syntax: '<table><tr><th>H</th></tr><tr><td>D</td></tr></table>', description: 'table contains tr (rows), tr contains th/td (cells).', returnType: 'N/A', details: 'table > tr > th or td. th for headers (bold by default), td for data. Use thead/tbody/tfoot for structure.' },
  { category: 'HTML', tag: 'table', item: 'caption', syntax: '<table><caption>Title</caption>...</table>', description: 'Table title/caption.', returnType: 'N/A', details: 'caption should be first or last child of table. Describes the table for accessibility.' },

  { category: 'HTML', tag: 'paths', item: 'Relative path ./', syntax: 'href="./file.html"', description: 'Current directory.', returnType: 'N/A', details: './ means current directory. ./file.html is file in same folder as the current page.' },
  { category: 'HTML', tag: 'paths', item: 'Relative path ../', syntax: 'href="../file.html"', description: 'Parent directory.', returnType: 'N/A', details: '../ means parent directory. ../file.html goes up one level then to file.html.' },
  { category: 'HTML', tag: 'paths', item: 'Root path /', syntax: 'href="/file.html"', description: 'Root of site or server.', returnType: 'N/A', details: '/ at start means root. /file.html is at the root of the domain or app.' },
  { category: 'HTML', tag: 'paths', item: 'Absolute URL', syntax: 'href="https://example.com/page"', description: 'Full URL to another site or resource.', returnType: 'N/A', details: 'Full URL includes protocol. Use for external links. Consider target="_blank" and rel="noopener" for external.' },
  { category: 'HTML', tag: 'paths', item: 'Anchor in page', syntax: 'id="section1"  and  href="#section1"', description: 'Link to a specific element on the same page.', returnType: 'N/A', details: 'Give element an id, then link with href="#id". Browser scrolls to that element.' },

  { category: 'HTML', tag: 'attributes', item: 'class', syntax: 'class="box primary"', description: 'Space-separated list of CSS classes.', returnType: 'N/A', details: 'class can have multiple values. Used for styling and JS selection. Not unique.' },
  { category: 'HTML', tag: 'attributes', item: 'data-* attributes', syntax: 'data-id="123"', description: 'Custom data attributes for JS; no semantic meaning.', returnType: 'N/A', details: 'data-* attributes are valid HTML5. Access in JS via element.dataset.id (data-id).' },
  { category: 'HTML', tag: 'attributes', item: 'title', syntax: 'title="tooltip text"', description: 'Tooltip shown on hover.', returnType: 'N/A', details: 'title shows as native tooltip. Do not rely for critical info; not available on keyboard-only or touch.' },
  { category: 'HTML', tag: 'attributes', item: 'tabindex', syntax: 'tabindex="0"  or  tabindex="-1"', description: 'Control tab order and focusability.', returnType: 'N/A', details: 'tabindex="0" includes in natural order; -1 allows programmatic focus but not tab. Positive values avoid.' },

  // ========== Node.js & Modules ==========
  {
    category: 'Node.js & Modules',
    item: 'require()',
    syntax: 'const x = require("module");',
    description: 'CommonJS: load a module.',
    returnType: 'Exported value of the module',
    details: 'require() is synchronous. Returns whatever the module exports (module.exports).',
  },
  {
    category: 'Node.js & Modules',
    item: 'module.exports single',
    syntax: 'module.exports = xyz;',
    description: 'CommonJS: export a single value.',
    returnType: 'N/A',
    details: 'module.exports = xyz exports one value. Require returns that value directly.',
  },
  {
    category: 'Node.js & Modules',
    item: 'module.exports object',
    syntax: 'module.exports = { a, b };',
    description: 'CommonJS: export multiple named values.',
    returnType: 'N/A',
    details: 'module.exports = { a, b } exports an object. Require returns the object; use .a, .b to access.',
  },
  {
    category: 'Node.js & Modules',
    item: 'import (ES Modules)',
    syntax: 'import x from "module";  import { a, b } from "module";',
    description: 'ES Modules: load module or named exports.',
    returnType: 'N/A',
    details: 'import is static (top-level). import x for default export; import { a, b } for named exports.',
  },
  {
    category: 'Node.js & Modules',
    item: 'export (ES Modules)',
    syntax: 'export const a = 1;  export { a, b };',
    description: 'ES Modules: expose named values.',
    returnType: 'N/A',
    details: 'export exposes names. Can use export const/function or export { a, b } at end of file.',
  },
  {
    category: 'Node.js & Modules',
    item: 'export default',
    syntax: 'export default value;',
    description: 'ES Modules: single default export.',
    returnType: 'N/A',
    details: 'Only one default per module. Import with import name from "module" (any name).',
  },
  {
    category: 'Node.js & Modules',
    item: '__dirname',
    syntax: '__dirname',
    description: 'Absolute path of the directory containing the current file.',
    returnType: 'string (path)',
    details: '__dirname is available in CommonJS. In ES modules use import.meta.url and path/dirname to get directory. __dirname is not available in browser.',
  },
  {
    category: 'Node.js & Modules',
    item: '__filename',
    syntax: '__filename',
    description: 'Absolute path of the current file.',
    returnType: 'string (path)',
    details: '__filename is CommonJS only. In ESM use import.meta.url. Contains full path including filename.',
  },
  {
    category: 'Node.js & Modules',
    item: 'require vs import',
    syntax: 'require() at runtime  |  import at parse time',
    description: 'CommonJS is dynamic; ESM is static.',
    returnType: 'N/A',
    details: 'require() can be conditional or in middle of file. import is hoisted and must be at top; can use dynamic import() for async load.',
  },
  {
    category: 'Node.js & Modules',
    item: 'path module',
    syntax: 'const path = require("path");  path.join(a, b)  path.resolve(a)',
    description: 'Utilities for file paths.',
    returnType: 'string (path)',
    details: 'path.join() joins with OS separator. path.resolve() resolves to absolute. path.dirname(), path.basename(), path.extname().',
  },
  {
    category: 'Node.js & Modules',
    item: 'fs module',
    syntax: 'const fs = require("fs");  fs.readFileSync(path)  fs.writeFileSync(path, data)',
    description: 'Synchronous file read/write.',
    returnType: 'Buffer/string or void',
    details: 'fs.readFileSync returns file contents. fs.writeFileSync writes. Use async versions (fs.promises) in server to avoid blocking.',
  },

  // ========== Express.js ==========
  {
    category: 'Express.js',
    item: 'server.get',
    syntax: 'server.get(path, handler)',
    description: 'Register handler for GET requests to path.',
    returnType: 'N/A',
    details: 'server.get(path, handler) — handler runs when HTTP method is GET and path matches. Use for reading data.',
  },
  {
    category: 'Express.js',
    item: 'server.post',
    syntax: 'server.post(path, handler)',
    description: 'Register handler for POST requests to path.',
    returnType: 'N/A',
    details: 'server.post(path, handler) — handler runs when HTTP method is POST and path matches. Use for submitting data.',
  },
  {
    category: 'Express.js',
    item: 'server.put / patch / delete',
    syntax: 'server.put(path, handler)  server.delete(path, handler)',
    description: 'Register handlers for PUT, PATCH, DELETE.',
    returnType: 'N/A',
    details: 'Same pattern as get/post. put = full replace, patch = partial update, delete = remove resource.',
  },
  {
    category: 'Express.js',
    item: 'req.query',
    syntax: 'req.query',
    description: 'GET query parameters (from URL ?key=value).',
    returnType: 'Object',
    details: 'req.query holds parsed query string. For GET /search?q=hello, req.query.q is "hello". No middleware needed.',
  },
  {
    category: 'Express.js',
    item: 'req.body',
    syntax: 'req.body',
    description: 'POST (or PUT/PATCH) body data.',
    returnType: 'Object (when parsed)',
    details: 'req.body contains parsed body. Requires middleware: express.json() for JSON, express.urlencoded({ extended: true }) for form data.',
  },
  {
    category: 'Express.js',
    item: 'req.params',
    syntax: 'req.params',
    description: 'Route parameters from path (e.g. /user/:id).',
    returnType: 'Object',
    details: 'req.params has keys from route placeholders. For route /user/:id and URL /user/5, req.params.id is "5".',
  },
  {
    category: 'Express.js',
    item: 'req.headers',
    syntax: 'req.headers',
    description: 'Request headers (lowercased keys).',
    returnType: 'Object',
    details: 'req.headers["content-type"], req.get("Content-Type"). Read-only object of incoming headers.',
  },
  {
    category: 'Express.js',
    item: 'res.send()',
    syntax: 'res.send(body)',
    description: 'Send a response (text, HTML, Buffer, or object).',
    returnType: 'N/A',
    details: 'res.send() can send string (sets Content-Type text/html by default for strings), Buffer, or object (as JSON). Ends the response.',
  },
  {
    category: 'Express.js',
    item: 'res.json()',
    syntax: 'res.json(obj)',
    description: 'Send JSON response.',
    returnType: 'N/A',
    details: 'res.json() sets Content-Type to application/json and sends the object as JSON. Use for APIs.',
  },
  {
    category: 'Express.js',
    item: 'res.render()',
    syntax: 'res.render(view, locals)',
    description: 'Render a view template (e.g. EJS) and send HTML.',
    returnType: 'N/A',
    details: 'res.render() is for server-side templates (EJS, Pug). Pass view name and data object. Sends rendered HTML.',
  },
  {
    category: 'Express.js',
    item: 'res.redirect()',
    syntax: 'res.redirect(status, url)  or  res.redirect(url)',
    description: 'Redirect client to another URL.',
    returnType: 'N/A',
    details: 'res.redirect() sends 302 (or specified status) and Location header. Browser makes new request to that URL.',
  },
  {
    category: 'Express.js',
    item: 'res.status()',
    syntax: 'res.status(404).send("Not found")',
    description: 'Set HTTP status code.',
    returnType: 'Response (chainable)',
    details: 'res.status(code) sets status. Chain with send/json/render. 200 OK, 201 Created, 404 Not Found, 500 Server Error.',
  },
  {
    category: 'Express.js',
    item: 'express.static',
    syntax: 'express.static("public")',
    description: 'Serve static files from a directory.',
    returnType: 'Middleware function',
    details: 'express.static("public") serves files from the "public" folder. Request to /style.css maps to public/style.css. No URL path change unless mounted.',
  },
  {
    category: 'Express.js',
    item: 'express.urlencoded',
    syntax: 'express.urlencoded({ extended: true })',
    description: 'Parse URL-encoded form body (POST form data).',
    returnType: 'Middleware function',
    details: 'Middleware to parse application/x-www-form-urlencoded (form submit). extended: true uses qs library for nested objects. Populates req.body.',
  },
  {
    category: 'Express.js',
    item: 'express.json()',
    syntax: 'express.json()',
    description: 'Parse JSON request body.',
    returnType: 'Middleware function',
    details: 'Middleware to parse Content-Type: application/json. Populates req.body. Must use before routes that need req.body.',
  },
  {
    category: 'Express.js',
    item: 'app.use()',
    syntax: 'app.use(middleware)  or  app.use(path, middleware)',
    description: 'Mount middleware or router for all (or path-prefixed) requests.',
    returnType: 'N/A',
    details: 'app.use() runs for every request (or every request to path). Order matters; put body parsers and static before routes.',
  },

  // ========== EJS Templating ==========
  {
    category: 'EJS Templating',
    item: 'Escaped output',
    syntax: '<%= variable %>',
    description: 'Output variable value, HTML-escaped (safe from XSS).',
    returnType: 'N/A',
    details: '<%= variable %> escapes HTML so user input is safe. Use for any user-provided or untrusted data.',
  },
  {
    category: 'EJS Templating',
    item: 'Unescaped output',
    syntax: '<%- variable %>',
    description: 'Output raw HTML (no escaping).',
    returnType: 'N/A',
    details: '<%- variable %> does not escape — XSS risk. Only use when you trust the content (e.g. your own HTML).',
  },
  {
    category: 'EJS Templating',
    item: 'Logic tags',
    syntax: '<% logic %>',
    description: 'Execute JavaScript (loops, conditionals); no output.',
    returnType: 'N/A',
    details: '<% %> runs JS but does not output. Use for if, for, while, etc. Use <%= %> or <%- %> when you want to print.',
  },
  {
    category: 'EJS Templating',
    item: 'View engine setting',
    syntax: "server.set('view engine', 'ejs');",
    description: 'Set EJS as the default view engine.',
    returnType: 'N/A',
    details: "server.set('view engine', 'ejs') tells Express to use .ejs extension and EJS for res.render().",
  },
  {
    category: 'EJS Templating',
    item: 'Views directory',
    syntax: "server.set('views', path.join(__dirname, 'views'));",
    description: 'Directory where template files live.',
    returnType: 'N/A',
    details: "Default is ./views. res.render('page') looks for views/page.ejs when view engine is ejs.",
  },
  {
    category: 'EJS Templating',
    item: 'Include partials',
    syntax: '<%- include("header") %>',
    description: 'Include another EJS file (e.g. header, footer).',
    returnType: 'N/A',
    details: 'include() inserts the file. Use <%- include("partial") %> for raw output. Path relative to views folder.',
  },
  {
    category: 'EJS Templating',
    item: 'Pass locals to include',
    syntax: '<%- include("item", { item }) %>',
    description: 'Pass data into included template.',
    returnType: 'N/A',
    details: 'Second argument to include() is object of local variables. That partial can use item, etc.',
  },
  {
    category: 'EJS Templating',
    item: 'EJS for loop',
    syntax: '<% for (let i = 0; i < items.length; i++) { %>\n  <%= items[i] %>\n<% } %>',
    description: 'Loop over array by index in EJS.',
    returnType: 'N/A',
    details: 'Use <% %> for loop logic; use <%= %> inside to output each value. No output from <% %> tags.',
  },
  {
    category: 'EJS Templating',
    item: 'EJS for...of loop',
    syntax: '<% for (const item of items) { %>\n  <%= item %>\n<% } %>',
    description: 'Loop over array values in EJS.',
    returnType: 'N/A',
    details: 'for...of gives each element. Use <%= item %> to render. Same pattern: logic in <% %>, output in <%= %>.',
  },
  {
    category: 'EJS Templating',
    item: 'EJS forEach loop',
    syntax: '<% items.forEach(function(item) { %>\n  <%= item %>\n<% }); %>',
    description: 'Loop using forEach in EJS.',
    returnType: 'N/A',
    details: 'items.forEach(cb) — inside <% %>. Use <%= item %> in body to output. Arrow: items.forEach(item => { %> ... <% });',
  },
  {
    category: 'EJS Templating',
    item: 'EJS if / else',
    syntax: '<% if (user) { %><%= user.name %><% } else { %>Guest<% } %>',
    description: 'Conditional output in EJS.',
    returnType: 'N/A',
    details: 'if/else in <% %>; output with <%= %> in each branch. No output from the if/else tags themselves.',
  },
  {
    category: 'EJS Templating',
    item: 'EJS if / else if / else',
    syntax: '<% if (x > 0) { %>positive<% } else if (x < 0) { %>negative<% } else { %>zero<% } %>',
    description: 'Multiple conditions in EJS.',
    returnType: 'N/A',
    details: 'Same as if/else; add else if (condition) { } blocks. Use <%= variable %> when you need to output a value.',
  },
];
